### ISSUE TITLE
[2주차] 기본 과제 & 심화 과제

### ISSUE THREAD

**Issue by hwangsunwoong** [DO-SOPT-SERVER/SunwoongH#3]
## Issue ☃️
2주차 기본 과제 & 심화 과제

## Todo ✔️
- [x] 2주차 세미나 이론 & 코드 복습하기
- [x] dto -> record 사용해서 구현하기
- [x] crud API 구현하기
